# Generated by Django 5.1.2 on 2024-11-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
